# Generated by Django 2.2.6 on 2019-11-17 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Songs',
        ),
    ]
