# Generated by Django 2.2.6 on 2019-11-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('songs', '0002_delete_songs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('logo', models.ImageField(default='default.jpg', upload_to='media/')),
                ('file', models.FileField(upload_to='media/')),
                ('description', models.TextField()),
            ],
        ),
    ]
