# Generated by Django 2.2.6 on 2019-11-18 01:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='date_published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
